version: '3'

services:
  web:
    build: .
    image: nginx-environment
    restart: always
    container_name: web-container
    ports: 
      - "7400:80"
    volumes:
      - ./:/usr/share/nginx/html